#!/usr/bin/env python
import pip
import sys
import os.path
from typing import List

# List of package sources, ordered by priority (most important first)
# n.b., PyPI will effectively catch everything, so must be last
import ypip.sources as sources
_sources = [
    sources.RequirementsTxt(),
    sources.GitOnGithub(),
    sources.PyPI()
]

def usage(exit_code:int):
    print('\n'.join([
        'Usage: ypip [-u] [PACKAGE]',
        '',
        '-u       Upgrade all packages to the newest available version',
        'PACKAGE  The package string; this will default to requirements.txt'
    ]))

    sys.exit(exit_code)


def main(args:List[str]):
    req_file = 'requirements.txt'
    upgrade = False

    for arg in args:
        if arg in ['-h', '--help']:
            usage(0)
        elif arg == '-u':
            upgrade = True
        elif os.path.isfile(arg):
            req_file = arg
        else:
            usage(1)

    requirements = open(req_file).read().splitlines()
    print(requirements)


if __name__ == '__main__':
    main(sys.argv[1:])
