#!/usr/bin/env python
import pip
import sys
import os.path
from typing import List

from ypip.sources import RequirementsTxt, \
                         PyPI, \
                         GitOnGithub


# List of hosted VCS models
hosted_vcss = [RequirementsTxt(), PyPI(), GitOnGithub()]


def usage(exit_code:int):
    print('''Usage: ypip [-u] [REQUIREMENTS]

    -u            Upgrade all packages to the newest available version
    REQUIREMENTS  The requirements file; this will default to requirements.txt''')

    sys.exit(exit_code)


def main(args:List[str]):
    req_file = 'requirements.txt'
    upgrade = False

    for arg in args:
        if arg in ['-h', '--help']:
            usage(0)
        elif arg == '-u':
            upgrade = True
        elif os.path.isfile(arg):
            req_file = arg
        else:
            usage(1)

    requirements = open(req_file).read().splitlines()
    print(requirements)


if __name__ == '__main__':
    main(sys.argv[1:])
